#!/usr/bin/env python3

import argparse
import os
import json
import pathlib
import shutil
import csv

# Construct the argument parser
parser = argparse.ArgumentParser(description='Convert the block .json files in the NewPatch repository to .rst documentation.')
parser.add_argument('--path', '-p', help='The path to the blocks folder (NewPatch/Assets/Blocks)', default='../NewPatch/Assets/Blocks')
parser.add_argument('--clean', '-c', help='Removes all the files generated by this script', action='store_true', default=False)
parser.add_argument('--verbose', '-v', help='Print info to the terminal while running.', action='store_true', default=False)

# Parse the command line args
args = parser.parse_args()

# Attempt to load config for overrides
config = {}
config_path = 'wiki-integration/wiki-config.json'
if os.path.exists(config_path):
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
    except Exception:
        pass

# Determine blocks folder with fallback logic
blocksFolder = args.path
if not os.path.exists(blocksFolder):
    # Try config override
    if config.get('blocks_source_path'):
        blocksFolder = config['blocks_source_path']
    # Try alternative folder name (Patch2025 vs NewPatch)
    elif 'NewPatch' in blocksFolder:
        alt_path = blocksFolder.replace('NewPatch', 'Patch2025')
        if os.path.exists(alt_path):
            blocksFolder = alt_path
    elif 'Patch2025' in blocksFolder:
        alt_path = blocksFolder.replace('Patch2025', 'NewPatch')
        if os.path.exists(alt_path):
            blocksFolder = alt_path

verbose = args.verbose

if verbose:
    print(f'Checking if the given blocks folder {blocksFolder} exists')

# Check if the given path exists
if not os.path.exists(blocksFolder):
    print(f'Error: the given path to the Blocks folder ({blocksFolder}) could not be found. \n\nPlease check if the documentation and Unity repositories (NewPatch or Patch2025) reside in the same folder. Alternatively, supply the correct path using the --path PATH command line option.')

if verbose:
    print('Cleaning the Blocks folder')

for root, dirs, files in os.walk('source/Blocks'):
    if root != 'source/Blocks':
        for f in files:
            path = os.path.join(root, f)

            if verbose:
                print(f'Removing {path}')

            os.remove(path)

for root, dirs, files in os.walk('source/Blocks'):
    for f in files:
        path = os.path.join(root, f)

        if verbose:
            print(f'Removing {path}')

        os.remove(path)

    if root != 'source/Blocks':
        if verbose:
            print(f'Removing directory {root}')

        shutil.rmtree(root)

# Add these constants near the top of the file
THUMBNAILS_SOURCE = '../NewPatch/Assets/StreamingAssets/Thumbnails/Blocks'
if config.get('thumbnails_path'):
    THUMBNAILS_SOURCE = config['thumbnails_path']
elif not os.path.exists(THUMBNAILS_SOURCE):
    alt_thumbnails = THUMBNAILS_SOURCE.replace('NewPatch', 'Patch2025')
    if os.path.exists(alt_thumbnails):
        THUMBNAILS_SOURCE = alt_thumbnails
THUMBNAILS_DEST = 'source/_static/block-thumbnails'

# Create thumbnails destination directory if it doesn't exist
pathlib.Path(THUMBNAILS_DEST).mkdir(parents=True, exist_ok=True)

# Reads and parses the given file from JSON into a dictionary
def readAndParseBlockJson(path):
    with open(path, 'r') as f:
        text = f.read()
        block = json.loads(text)
        return block

blocks = []

if verbose:
    print(f'Reading and parsing block files')

# We'll add this function near the top with the other functions
def get_menu_path_from_file_path(file_path, blocks_folder):
    """Extract menu path from the block's file location relative to blocks folder"""
    # Remove the blocks folder prefix and any leading/trailing slashes
    relative_path = os.path.relpath(os.path.dirname(file_path), blocks_folder)
    if relative_path == '.':
        return ''
    return relative_path.replace('\\', '/')

# Add this function with the other utility functions
def find_thumbnail(block_name, thumbnails_dir):
    """Find the thumbnail image for a block, returns None if not found"""
    # Common image extensions to try
    extensions = ['.png', '.jpg', '.jpeg']
    
    # Try exact name match first
    for ext in extensions:
        image_path = os.path.join(thumbnails_dir, block_name + ext)
        if os.path.exists(image_path):
            return image_path
            
    # Try case-insensitive match
    block_name_lower = block_name.lower()
    for filename in os.listdir(thumbnails_dir):
        name, ext = os.path.splitext(filename)
        if ext.lower() in ['.png', '.jpg', '.jpeg'] and not filename.endswith('.meta'):
            if name.lower() == block_name_lower:
                return os.path.join(thumbnails_dir, filename)
    
    return None

for root, dirs, files in os.walk(blocksFolder):
    for file in files:
        if root == blocksFolder:
            continue

        if file.endswith('.json'):
            path = os.path.join(root, file)

            try:
                if verbose:
                    print(f'Reading and parsing {path}')

                block = readAndParseBlockJson(path)
                block['menuPath'] = get_menu_path_from_file_path(path, blocksFolder)
                block['sourceJsonPath'] = path

                # Find and process thumbnail
                thumbnail_path = find_thumbnail(block['name'], THUMBNAILS_SOURCE)
                if thumbnail_path:
                    filename = os.path.basename(thumbnail_path)
                    block['thumbnailImage'] = f'block-thumbnails/{filename}'
                    
                    # Copy the thumbnail file
                    dest_path = os.path.join(THUMBNAILS_DEST, filename)
                    if verbose:
                        print(f'Copying thumbnail {filename}')
                    shutil.copy2(thumbnail_path, dest_path)
                else:
                    block['thumbnailImage'] = None
                    if verbose:
                        print(f'No thumbnail found for {block["name"]}')
                
                blocks.append(block)
            except Exception as e:
                print(f'Error while reading and parsing file {path}.')
                print(e)

# Takes a block description dictionary and outputs a string with
# the generated .rst documentation.
def generateRstDocumentationForBlock(block):
    result = ''

    # Title
    result += block['name'] + '\n'
    result += ''.join(['=' for c in block['name']]) + '\n\n'
    result += f'.. _{block["name"]}:\n\n'

    # Description
    result += '**Description**\n\n'
    result += block['description'] + '\n\n'

    if 'longDescription' in block:
        result += block['longDescription'] + '\n\n'

    # Inputs
    result += '**Inputs, output and other parts**\n\n'
    
    for part in block['parts']:
        typeString = f' ({part["type"]})' if part['type'] != "" else ""
        result += f'*{part["name"]}*{typeString} {part["description"]}\n\n'

    relatedBlocks = block['relatedBlocks']
        
    if len(relatedBlocks) > 0:
        result += '**See also:**\n\n'

        # Modified this section - relatedBlocks are already strings
        relatedBlockLinks = [f':ref:`{name} <{name}>`' for name in relatedBlocks]
        result += ', '.join(relatedBlockLinks) + "\n\n"

    return result

# Utility function that gets a block by name, e.g. 's_mul'. Used
# for debugging.
def getBlockByName(blocks, name):
    return [b for b in blocks if b['name'] == name][0]

if verbose:
    print(f'Generating documentation')

for block in blocks:
    if verbose:
        print(f'Generating documentation for {block["name"]}')

    if block['includeInWebDocumentation']:
        rst = generateRstDocumentationForBlock(block)

        dir = os.path.join('source/Blocks/', block['menuPath'])

        pathlib.Path(dir).mkdir(parents=True, exist_ok=True)

        path = os.path.join(dir, block['name'] + '_generated.rst')

        with open(path, 'w') as f:
            f.write(rst)

# After processing all blocks, create a consolidated JSON file
if verbose:
    print(f'Generating consolidated JSON file')

# Add docFile paths to blocks (removed the web_blocks filter)
for block in blocks:
    doc_path = f"Blocks/{block['menuPath']}/{block['name']}_generated.rst"
    block['docFile'] = doc_path

# Create the output data structure with all blocks
output_data = {
    "blocks": blocks  # Using all blocks instead of web_blocks
}

# Write the consolidated JSON file
json_output_path = 'source/blocks_data.json'
with open(json_output_path, 'w') as json_file:
    json.dump(output_data, json_file, indent=2)

if verbose:
    print(f'Wrote consolidated JSON to {json_output_path}')

# Generate a spreadsheet for all blocks
if verbose:
    print('Generating spreadsheet for all blocks')

# Find the maximum number of parts to create columns for
max_parts = 0
if blocks:
    max_parts = max(len(b.get('parts', [])) for b in blocks)

csv_output_path = 'blocks_datasheet.csv'
# Start with the base headers
csv_headers = [
    'name',
    'displayName',
    'sourceJsonPath',
    'description',
    'longDescription',
    'categories',
    'relatedBlocks',
    'includeInWebDocumentation'
]

# Add the dynamic part headers
for i in range(max_parts):
    csv_headers.append(f'part_{i+1}_name')
    csv_headers.append(f'part_{i+1}_description')
    csv_headers.append(f'part_{i+1}_type')

try:
    with open(csv_output_path, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_headers, extrasaction='ignore')
        writer.writeheader()
        for block in blocks:
            row_data = {
                'name': block.get('name'),
                'displayName': block.get('displayName'),
                'sourceJsonPath': block.get('sourceJsonPath'),
                'description': block.get('description', ''),
                'longDescription': block.get('longDescription', ''),
                'categories': json.dumps(block.get('categories', [])),
                'relatedBlocks': json.dumps(block.get('relatedBlocks', [])),
                'includeInWebDocumentation': block.get('includeInWebDocumentation', False)
            }
            
            # Add the parts data as flattened columns
            for i, part in enumerate(block.get('parts', [])):
                row_data[f'part_{i+1}_name'] = part.get('name', '')
                row_data[f'part_{i+1}_description'] = part.get('description', '')
                row_data[f'part_{i+1}_type'] = part.get('type', '')

            writer.writerow(row_data)

    if verbose:
        print(f'Successfully created spreadsheet at {csv_output_path}')
except Exception as e:
    print(f'Error creating spreadsheet: {e}')

if verbose:
    print(f'Reading Blocks.rst template')

# Read the Blocks.rst template file
blocksTocTreeTemplate = ''

with open('Blocks_template.rst', 'r') as f:
    blocksTocTreeTemplate = f.read()

if verbose:
    print(f'Generating toc tree')

# Generate the blocks toctree item string
blocksTocTreeItems = ''

for block in blocks:
    blocksTocTreeItems += f'   Blocks/{block["menuPath"]}/{block["name"]}\n'

# Replace the field in the template with the generated items
blocksTocTreeFile = blocksTocTreeTemplate.replace('{blocks-toctree-items}', blocksTocTreeItems)

if verbose:
    print(f'Writing Blocks.rst')

# Write the Blocks.rst file
with open('source/Blocks.rst', 'w') as f:
    f.write(blocksTocTreeFile)

if verbose:
    print(f'Reading subsection toc file template')

subfolderTocFileTemplate = ''

with open('blocks_subsection_template.rst', 'r') as f:
    subfolderTocFileTemplate = f.read()

# Make sure the blocks subdirs all have toctree files
for root, dirs, files in os.walk('source/Blocks'):
    p = pathlib.Path(root)

    pathToTocFile = pathlib.Path.joinpath(p.parent, p.name + '.rst')
    tocFileText = subfolderTocFileTemplate.replace('{title}', p.name.capitalize()).replace('{folder}', p.name)
    
    if verbose:
        print(f'Writing {pathToTocFile}')

    with open(pathToTocFile, 'w') as f:
        f.write(tocFileText)

if verbose:
    print(f'Done')